Downgraded to g++-5, as g++-6 causes library issues in clang
/usr/bin/clang++-4.0   -Dlibgalapix_EXPORTS -g -fPIC -I/home/travis/build/Galapix/galapix/src -I/home/travis/build/Galapix/galapix/build-Debug/src -isystem /home/travis/build/Galapix/galapix/external/logmich/include -isystem /home/travis/build/Galapix/galapix/external/glm -isystem /home/travis/build/Galapix/galapix/external/googletest/googletest/include -isystem /usr/include/ImageMagick    -std=c++1z -pedantic -Wall -Wextra -Wno-c++0x-compat -Wnon-virtual-dtor -Weffc++ -Wshadow -Wcast-qual -Winit-self -Wno-unused-parameter -Wunreachable-code -fopenmp -o CMakeFiles/libgalapix.dir/src/archive/rar.cpp.o -c /home/travis/build/Galapix/galapix/src/archive/rar.cpp
In file included from /home/travis/build/Galapix/galapix/src/archive/rar.cpp:19:
In file included from /home/travis/build/Galapix/galapix/src/archive/rar.hpp:22:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/vector:60:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/stl_algobase.h:64:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/stl_pair.h:59:
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/move.h:179:5: error:
      conflicting types for 'swap'
    swap(_Tp& __a, _Tp& __b)
    ^
/usr/bin/../lib/gcc/x86_64-linux-